Conquerblocksproject/blog/urls.py
from django.urls import path

from .views import blog_detail, blog_list

app_name = "blog"

urlpatterns = [
  path("", blog_list, name="blog_list"),
  path("<int:id>/", blog_detail, name="blog_detail"),
]

Conquerblocksproject/conquerblocks/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("cursos/", include("courses.urls", namespace="courses")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Conquerblocksproject/core/urls.py
from django.urls import path

from .views import home, about_us, register, login_view, contact, logout_view, search_view

app_name = "core"

urlpatterns = [
  path("", home, name="home"),
  path("sobre-nosotros/", about_us, name="about_us"),
  path("registro/", register, name="register"),
  path("search/", search_view, name="search"),
  path("login/", login_view, name="login"),
  path("logout/", logout_view, name="logout"),
  path("contacta-con-nosotros/", contact, name="contact"),
]

Conquerblocksproject/courses/urls.py
from django.urls import path

from .views import course_detail, course_list

app_name = "courses"

urlpatterns = [
  path("", course_list, name="course_list"),
  path("<int:id>/", course_detail, name="course_detail"),
]

Conquerblocksproject/conquerblocks/templates/_includes/_footer.html
<hr>
<p>© Conquer Blocks 2024</p>

Conquerblocksproject/conquerblocks/templates/_includes/_header.html
{% load static %}

<header>
  <a href="">
    <img style="width: 150px;" src="{% static 'img/logotipo-conquer-blocks.png' %}" alt="Logotipo de ConquerBlocks">
  </a>
</header>

<nav>
  {% include '_includes/_menu_principal.html' %}
</nav>

Conquerblocksproject/conquerblocks/templates/_includes/_menu_principal.html
<ul>
  <li><a href="{% url 'core:home' %}">Inicio</a></li>
  <li><a href="{% url 'core:about_us' %}">Sobre nosotros</a></li>
  <li><a href="{% url 'courses:course_list' %}">Cursos</a></li>
  <li><a href="{% url 'blog:blog_list' %}">Blog</a></li>
  <li><a href="{% url 'core:search' %}">Buscar</a></li>
  <li><a href="{% url 'core:register' %}">Registro</a></li>
  <li><a href="{% url 'core:contact' %}">Contacto</a></li>
  {% if request.user.is_authenticated %}
    <li><a href="{% url 'core:logout' %}">Cerrar sesión</a></li>
  {% endif %}
</ul>

<section class="user">
  {% if request.user.is_authenticated %}
    <p>Estás logueado como: {{ request.user }}</p>
  {% else %}
    <p><a href="{% url 'core:login' %}">Login</a></p>
  {% endif %}
</section>