Conquerblocksproject/blog/urls.py
from django.urls import path

from .views import blog_detail, blog_list

app_name = "blog"

urlpatterns = [
  path("", blog_list, name="blog_list"),
  path("<int:id>/", blog_detail, name="blog_detail"),
]

Conquerblocksproject/conquerblocks/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("cursos/", include("courses.urls", namespace="courses")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Conquerblocksproject/core/urls.py
from django.urls import path

from .views import home, about_us, register, login_view, contact, logout_view, search_view

app_name = "core"

urlpatterns = [
  path("", home, name="home"),
  path("sobre-nosotros/", about_us, name="about_us"),
  path("registro/", register, name="register"),
  path("search/", search_view, name="search"),
  path("login/", login_view, name="login"),
  path("logout/", logout_view, name="logout"),
  path("contacta-con-nosotros/", contact, name="contact"),
]

Conquerblocksproject/courses/urls.py
from django.urls import path

from .views import course_detail, course_list

app_name = "courses"

urlpatterns = [
  path("", course_list, name="course_list"),
  path("<int:id>/", course_detail, name="course_detail"),
]

Conquerblocksproject/core/models.py
from django.db import models
from django.utils import timezone

class Contact(models.Model):
    nombre = models.CharField(
        verbose_name='Nombre',
        max_length=50
    )
    email = models.EmailField(
        verbose_name='Email'
    )
    comentario = models.TextField(
        verbose_name='Comentario que ha dejado en la web'
    )
    created_at = models.DateTimeField(
        verbose_name='Fecha y hora de creación',
        default=timezone.now
    )
    contactado = models.BooleanField(
        verbose_name='¿Se ha contactado con él?',
        default=False
    )

    def __str__(self):
        return self.nombre

Conquerblocksproject/core/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password


class ContactForm(forms.Form):
    nombre = forms.CharField(max_length=50, label="Nombre")
    email = forms.EmailField(label="Email")
    comentario = forms.CharField(max_length=1000, label="Comentario", widget=forms.Textarea)

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if len(nombre) < 5:
            raise forms.ValidationError("El nombre debe tener al menos 5 caracteres")
        return nombre


class LoginForm(forms.Form):
    username = forms.CharField(max_length=140, label="Nombre de usuario")
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña")


class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=140, label="Nombre de usuario")
    first_name = forms.CharField(max_length=140, label="Nombre")
    last_name = forms.CharField(max_length=140, label="Apellidos")
    email = forms.EmailField(max_length=140, label="Email")

    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repita su contraseña', widget=forms.PasswordInput)


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 != password2 and password1 != '':
            raise forms.ValidationError('Las contraseñas no coinciden')

        if password2 != '':
            validate_password(password2)

        return password2

Conquerblocksproject/core/views.py
from django.shortcuts import render
from django.urls import reverse
# Create your views here.
from django.shortcuts import render

from courses.models import Course
from blog.models import Post
from .forms import ContactForm, LoginForm, UserRegisterForm
from django.core.mail import send_mail
from .models import Contact
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User

# Vistas generales de la aplicación
def home(request):
    context = {
        'courses': Course.objects.filter(show_home=True),
        'posts': Post.objects.filter(show_home=True)
    }
    return render(request, "core/home.html", context)

def about_us(request):
    return render(request, "core/about_us.html")

def search_view(request):
    print(request.GET.get('q'))  # Usa paréntesis en lugar de corchetes
    if 'q' in request.GET:  # Verifica si 'q' está en request.GET
        busqueda = request.GET.get('q')  # Usa paréntesis en lugar de corchetes
        cursos = Course.objects.filter(title__icontains=busqueda)
        print(cursos)
        context = {
            'courses': cursos  # Asegúrate de que la clave sea 'courses'
        }
        return render(request, "core/search.html", context)
    
    return render(request, "core/search.html")


def login_view(request):
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('core:home'))
            else:
                context = {
                  'form': form,
                  'error': True,
                  'error_message': 'Usuario no válido' 
                }
                return render(request, "core/login.html", context)
        else:
            context = {
                'form': form,
                'error': True
            }
            return render(request, "core/login.html", context)
    else:
        form = LoginForm()
        context = {
            'form': form
        }
        return render(request, "core/login.html", context)
    
def logout_view(request):
    logout(request)
    return redirect(reverse('core:home'))

def register(request):
    if request.POST:
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            user = User.objects.create_user(username, email, password2)
            if user:
                user.first_name = first_name
                user.last_name = last_name
                user.save()

            context = {
                'msj': 'Usuario creado correctamente'
            }

            return render(request, "core/register.html", context)
        else:
            context = {
                'form': form,
                'error': True
            }
            return render(request, "core/register.html", context)
    else:
        form = UserRegisterForm()
        context = {
            'form': form
        }
        return render(request, "core/login.html", context)



    return render(request, "core/register.html")

def contact(request):
    if request.POST:
        formulario = ContactForm(request.POST)

        if formulario.is_valid():
            nombre = formulario.cleaned_data['nombre']
            email = formulario.cleaned_data['email']
            comentario = formulario.cleaned_data['comentario']

            message_content = f'{nombre} con email {email} ha escrito lo siguiente: {comentario}'

            Contact.objects.create(
                nombre=nombre,
                email=email,
                comentario=comentario
            )

            success = send_mail(
                "Formulario de contacto de mi Web",
                message_content,
                "danielabrador47@gmail.com",
                ["danielabrador47@gmail.com"],
                fail_silently=False,
            )

            context = {
              'form' : formulario,
              'success' : success
            }
            return render(request, "core/contact.html", context)
        else:
            context = {
              'form' : formulario,
            }
            return render(request, "core/contact.html", context)
  
    formulario = ContactForm()
    context = {
      'form' : formulario
    }
    return render(request, "core/contact.html", context)

Conquerblocksproject/conquerblocks/templates/core/about_us.html
{% extends "layout-base.html" %}

{% block head_title %}Sobre nosotros{% endblock %}

{% block page_content %}
  <h1>Sobre nosotros</h1>
{% endblock %}

Conquerblocksproject/conquerblocks/templates/core/contact.html
{% extends "layout-base.html" %}

{% block head_title %}Contacto{% endblock %}

{% block page_content %}
  <h1>Contacto</h1>
  {% if success %}
    <p>Se ha enviado el formulario correctamente</p>
  {% else %}
    <form action="" method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <button>Enviar</button>
  </form>
  {% endif %}
{% endblock %}

Conquerblocksproject/conquerblocks/templates/core/home.html
{% extends "layout-base.html" %}

{% block head_title %}Página Home{% endblock %}

{% block page_content %}
  <h1>La escuela líder en habla hispana que revoluciona la educación en tecnología</h1>
  <p>Da un giro a tu futuro profesional guiado por los mayores referentes del sector</p>

  <h2>Descubre ConquerBlocks</h2>
  <p>La escuela número 1 en desarrollo de tecnologías emergentes. Conquer Blocks tiene un Máster pensado para ti</p>
  <p><a href="{% url 'core:about_us' %}">Conoce ConquerBlocks</a></p>

  <h2>Estudia con nosotros</h2>
  {% for course in courses %}
    <article id="{{ course.pk }}">
      <h3>{{ course.title }}</h3>
      <p>Fecha de creación: {{ course.created_at }}</p>
      {% if course.course_image %}
        <picture>
          <img src="{{ course.course_image.thumbnails.small.url }}" alt="">
        </picture>
      {% endif %}
      <div>
        {{ course.content|safe|truncatechars:100 }}...
      </div>
      <p><a href="{% url 'courses:course_detail' course.pk %}">Ver curso completo</a></p>
    </article>
  {% endfor %}


  <h2>Últimas noticias</h2>
  {% for post in posts %}
    <article id="{{ post.pk }}">
      <h3>{{ post.title }}</h3>
      <p>Fecha de publicación: {{ post.created_at }}</p>
      <div>
        {{ post.content|safe|truncatechars:100 }}...
      </div>
      <p><a href="{% url 'blog:blog_detail' post.pk %}">Ver noticia completa</a></p>
    </article>
  {% endfor %}


Conoce ConquerBlocks
{% endblock %}

Conquerblocksproject/conquerblocks/templates/core/login.html
{% extends "layout-base.html" %}

{% block head_title %}Login{% endblock %}

{% block page_content %}
  <h1>Login</h1>

  {% if error_message %}
    <p style="color: red;">{{ error_message }}</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Enviar</button>
  </form>
{% endblock %}

Conquerblocksproject/conquerblocks/templates/core/register.html
{% extends "layout-base.html" %}

{% block head_title %}Registro{% endblock %}

{% block page_content %}
  <h1>Registro</h1>
  {% if form  %}
    {% if error_message %}
      <p style="color: red;">{{ error_message }}</p>
    {% endif %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Enviar</button>
    </form>
  {% else %}
    <p>{{ msj }}</p>
  {% endif %}
{% endblock %}

Conquerblocksproject/conquerblocks/templates/core/search.html
{% extends "layout-base.html" %}

{% block head_title %}Search{% endblock %}

{% block page_tittle %}Bienvenido a nuestra página de búsqueda{% endblock %}

{% block page_content %}
  <p>Esta es la página para buscar</p>
  <div>
    <form action="" method="get">
        <h2>Busca cursos</h2>
        <div>
            <label for="">Introduce cualquier cadena de texto</label>
            <input type="text" name="q" required value="{% if request.GET %}{{ request.GET.q }}{% endif %}">
            <button>Buscar</button>
        </div>
    </form>
  </div>
  {% if request.GET %}
    <div>
      <h3>Resultados para la búsqueda con {{ request.GET.q }}</h3>
      {% if courses %}
      <ul>
        {% for course in courses %}
        <li>{{ course.title }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <p>No hay cursos para esa búsqueda</p>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}